### ISSUE TITLE
Add or update to IMBIE2 basins

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/geometric_features#100]
IMBIE2 basins are available as shape files here: http://imbie.org/imbie-2016/drainage-basins/

They may be preferable compared with the IMBIE1 basins, meaning we may want to replace existing basin definitions or add these new basins.

**Comment by xylar** [comment]
@stephenprice @matthewhoffman @tongzhangice, what do you think?  Is this a priority for any work you're doing?

**Comment by stephenprice** [comment]
@xylar, I would put this at a pretty low priority for right now. I don't think there's any harm in using the original IMBIE basins for the time being. Thanks for checking. What's the process for putting this on a "to do" list but with low priority?

**Comment by xylar** [comment]
I think having an issue on GitHub is the best way to remind me in the distant future that this is a thing and it still needs to happen.  So we'll just leave this lying around...

**Comment by xylar** [comment]
@hollyhan, obviously, we've been thinking of updating to IMBIE2 for 4 years or so...

**Comment by hollyhan** [comment]
@xylar, yay! I'm glad to be part of this update!

**Comment by xylar** [comment]
We have just added the ISMIP6 basins in #180.  These are similar to the IMBIE2 basins  but 4 IMBIE2 basins (Filchner and Ronne, East and West Ross)  are combined into 2 basins (FRIS and Ross).  The ISMIP6 basins are also extended onto the continental shelf and beyond (to accommodate ice advance).

@matthewhoffman, @stephenprice, @hollyhan and others, are the ISMIP6 basins sufficient or do we want the IMBIE2 basins, too?

**Comment by xylar** [comment]
Having not got feedback on this, I'll close it for now.

**Comment by matthewhoffman** [comment]
Thanks, @xylar , and sorry for letting this drop.  I think the ISMIP6 basins are sufficient.  The split FRIS and Ross basins could be useful in the future, but for now it has not been critical to have them.
