### ISSUE TITLE
setup_ocean_region_groups does not appear to work properly

### ISSUE THREAD

**Issue by milenaveneziani** [MPAS-Dev/geometric_features#107]
This came up because I am trying to create consistent MOC regions (ocean basin regions for which we wish to compute the MOC streamfunction and zonal MHT). The plan is to:
1) create the MOC regions feature collection, like we intended to in the beginning;
2) create the southern transect manually, looking at the southern transect in the features in 1) and adding many more points in between (to ensure a better transformation into a maskfile by MpasMaskCreator);
3) create the new maskfile from 1) and 2), to be used for the online/offline MOC (and eventually the online/offline MHT).

I started using `setup_ocean_region_groups` from the `examples/` folder to get to step 1). But I am getting a feature collection that is incorrect, in the sense that, instead of a `merge`, it seems more like a `combine` (only one huge feature is there).
I believe there is a similar problem for the oceanBasins geojson file.

**Comment by milenaveneziani** [comment]
After saving the intermediate-step features to file, I see that the very first MOC region (Atlantic_MOC) gets saved correctly:

![Screen Shot 2019-08-01 at 3 29 45 PM](https://user-images.githubusercontent.com/8237579/62329115-3467cc80-b472-11e9-9670-dc241f639119.png)

but then, for the second feature (IndoPacific_MOC) and right after these lines of code in `setup_ocean_region_groups`:
```
137         # add this basin to the full feature collection
138         fc.merge(fcBasin)
```
the result is a geojson file that is a combination of Altantic_MOC and IndoPacific_MOC in terms of coordinates/polygons, but with *only* one feature in it, still called `Atlantic_MOC`.

**Comment by xylar** [comment]
@milena, I'm not able to reproduce this.  I get a file called `MOCBasins.geojson` that contains all 4 MOC basins, as expected.

**Comment by milenaveneziani** [comment]
hmm, interesting.. And did you use the `setup_ocean_region_groups` that is currently in `examples\`?

**Comment by xylar** [comment]
Yep, I'm using the current `MPAS-Dev/geometric_features/master`

**Comment by xylar** [comment]
Is it possible that you're running from an environment that already has `geometric_features` installed as a package (e.g. the latest `e3sm-unified` 1.2.6)?  I'm not sure that would explain the problem, since the script should work with that `geometric_features` but I'm just trying to check whatever I can think of.

**Comment by milenaveneziani** [comment]
So, I don't really know what happened.. I re-ran the script just prepending `./` to it and things work now..

**Comment by milenaveneziani** [comment]
and thinking I wasted so much time on this yesterday. Bah.. Anyways, I'll close this now, thanks for checking this @xylar

**Comment by milenaveneziani** [comment]
@xylar : do you agree with the plan that I outlined above? (points 1) 2) 3))

**Comment by xylar** [comment]
@milenaveneziani, you can definitely do that.  The tool I added to MPAS-Tools is supposed to take care of 2) so it might be good to figure out whether it works or if we really do have to do the southern transect manually (a nightmare in the long run!).

**Comment by milenaveneziani** [comment]
>The tool I added to MPAS-Tools is supposed to take care of 2) so it might be good to figure out whether it works 

yes, that was this PR:
https://github.com/MPAS-Dev/MPAS-Tools/pull/147
If you scroll to the end, you will see there that we found out things were not working with the high-res mesh. We could try to revisit what the problems were, but do you have time for it? I could probably put aside 1 day of next week, if you think you'll have a spare day. Let's talk more on the phone, if a phone call is easy for you next week.
