### ISSUE TITLE
Version of coastline data?

### ISSUE THREAD

**Issue by mark-petersen** [MPAS-Dev/geometric_features#121]
I am looking for the name of the dataset that we use for the coastlines for culling land cells from global meshes. It is this file:

https://github.com/MPAS-Dev/geometric_features/blob/master/geometric_data/natural_earth/region/Land_Coverage/region.geojson

which only has a label of
```
            "properties": {
                "name": "Land Coverage",
                "tags": "",
                "object": "region",
                "component": "natural_earth",
                "author": "http://www.naturalearthdata.com/"
```

I suspect it is 10m coastline data set found here:
https://www.naturalearthdata.com/downloads/10m-physical-vectors/10m-coastline/

Does anybody know? We should add the name and also a version number, if possible, to the meta data.

**Comment by xylar** [comment]
I agree.  Doug Jacobsen is likely the one who added this and I doubt he would remember.  Maybe you can figure it out based on the number of polygons in the data set or something like that.

**Comment by mark-petersen** [comment]
Doug answered by email:
> I added the features back in August of 2015 (https://github.com/MPAS-Dev/geometric_features/commits/master?after=7e98575c9f396715075cf2c53a98b5a6e6800272+244)
>
> The oldest release that Natural Earth has was released in September of 2016.
>
> So, they don't have any information online about the release I used to initialize the features. I feel like I used whatever the highest resolution was at the time, but I don't see any information helping to point at what that was.

It looks like the Natural Earth data set has changed since 2015, so we would either need to do some detective work to figure out which dataset was used by today's naming conventions, or better yet, download a current version of the data and go forward.

Looking at the current region.geojson file, it is definitely not 10m. The current options are 10, 50, or 110m, but our file looks even lower resolution, maybe 500m:
![image](https://user-images.githubusercontent.com/4036816/67860519-abe5e000-fae3-11e9-8eeb-10d0c6bc92db.png)
![image](https://user-images.githubusercontent.com/4036816/67860559-c455fa80-fae3-11e9-8307-42c7d9a8494c.png)

Also, the download is in a *.shp, and would need to be converted to *.geojson. There are tools for that.

**Comment by mark-petersen** [comment]
This question is sufficiently answered. I think we would need to start fresh with a new dataset to add a version number to that file.
