### ISSUE TITLE
Plotting script does not exclude islands

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/geometric_features#43]
As discussed in https://github.com/MPAS-Dev/geometric_features/issues/41, our current plotting script does not exclude holes in Polygons and consequently shades islands.

cc @xylar

**Comment by xylar** [comment]
I'll look into this when I get a chance.  @pwolfram, if you have time to investigate, that would be good, too.    Polygons and multipolygons are stored as a list of shapes, the first of which is the outline and the rest of which are the holes.  I suspect that only the first polygon is being used or that the holes are being treated incorrectly as normal polygons.  But I haven't investigated.

It would be nice if we didn't have to do so much of the plot setup ourselves.  For example, there's a library called Descartes that can do standard matplotlib plots directly from shapely objects but I don't think it can do fancy transformations and maps like we're using.

**Comment by pwolfram** [comment]
@xylar, you are right that the first list of points in `coordinates` is the outer polygon and the next items in the list are holes.

I started to investigate this over the weekend but didn't fully get to a viable solution.  I would like to have one more stab before sharing my code.  How quickly do we need this fix @xylar and @milenaveneziani?

It appears we need to use something like `descartes` to convert the polygons to `matplotlib` patches but I wasn't able to get this to work properly and probably need more time for debugging.

**Comment by pwolfram** [comment]
Preliminary work is at https://github.com/pwolfram/geometric_features/tree/fix_island_plotting_bug

**Comment by douglasjacobsen** [comment]
@pwolfram This should be a low priority, as there are alternate methods of plotting that capture the holes correctly. But I think you can spend whatever time you want on fixing it.

**Comment by xylar** [comment]
Yep, super low priority.  It's just a convenience that we'd like to be able to plot our regions to verify that we're producing what we want.  Given we can use http://geojson.io/ or GitHub itself to view the files, it's not critical.

**Comment by xylar** [comment]
@pwolfram, one other plotting issue you might look into is that I accidentally merged some transects and regions into the same geojson file (happened to be everything with the tag `Mediterranean_Basin`) and it looked like the transects were getting plotted as polygons instead of lines.  Presumably this is a separate bug but while you're working on plotting...

If you can't recreate this issue, let me know and I'll try.

**Comment by pwolfram** [comment]
@xylar, can you please double-check to see if this transects issue still exists following #45?  I think this should fix this issue too...

**Comment by xylar** [comment]
This issue is addressed by #48.
