### ISSUE TITLE
Islands are included in the definitions of many ocean regions

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/geometric_features#44]
Depending on the application, these islands could potentially contribute erroneously to the total area of an ocean region, and should be excluded.

**Comment by xylar** [comment]
An example:
https://github.com/MPAS-Dev/geometric_features/blob/master/ocean/region/Southern_Ocean/region.geojson

Tasmania and New Zealand should not be part of the `Southern_Ocean` region

**Comment by douglasjacobsen** [comment]
I wonder if differencing regions with
https://github.com/MPAS-Dev/geometric_features/tree/master/natural_earth/region/Land_Coverage 
would provide a fix.

Though, perhaps we need a higher resolution definition of coast lines.

**Comment by douglasjacobsen** [comment]
I should mention, I used that land coverage region as an example because that's what we use to cull the ocean meshes.

**Comment by xylar** [comment]
@douglasjacobsen, I was thinking the same.  I think the one complication is that the coastlines might not quite match up in some places.  So what i would ideally do is first "grow" each region by a buffer zone (say 10 km), then, difference out all the neighboring seas and the land coverage.  I'll think about weird corners if that could cause a problem.

**Comment by xylar** [comment]
Here's an example of what goes wrong with a simple application of:
```
./difference_features.py -f ocean/region/Southern_Ocean/region.geojson \
-m natural_earth/region/Land_Coverage/region.geojson -o SouthernOcean.geojson
```
https://gist.github.com/xylar/3af3bdcf0552962c64f6a5dd1f9b5008

It looks great in most places (e.g. Argentina, the Falkland Islands) but if you zoom in on Tasmania and New Zealand, you see a little halo of junk that should be part of the Tasman Sea or some other region.  Thus the need to expand each sea a little bit toward the land before applying this method.

**Comment by xylar** [comment]
No, on further thought, you don't know where "land" is to expand into it in cases where islands are erroneously included.  So that approach wouldn't work.  I think the clean up approach will have to be to identify all these tiny little polygons and find out if they border another sea and add move them if so.  Should be possible to automate if we know that the "real" sea is one contiguous polygon (with holes).

**Comment by xylar** [comment]
Anyway, too big a project for 11:30 pm on a Monday.

**Comment by pwolfram** [comment]
@xylar and @douglasjacobsen, did the original sources have the islands correct or has the workflow somehow removed them?

**Comment by xylar** [comment]
@pwolfram, in this particular example, there was no Southern Ocean region in the original source.  I created one by making a rectangle and masking out existing regions from it.  This left islands.

**Comment by xylar** [comment]
In other cases (e.g. smaller islands in the Atlantic), these were just not excluded from the original source so not introduced as part of processing regions as far as I recall.

**Comment by xylar** [comment]
I have really been working hard on this one but I'm having trouble getting results that shapely thinks are valid.

My approach has been to gradually expand each sea but mask it by its neighboring seas and by the land coverage.  This should fill in the little gaps between land and ocean regions without ending up with overlap.  However, there are some seemingly pathological bits of topology that keep cropping up when I grow regions and I don't seem to be able to figure out where they're coming from or how to get rid of them.

Anyway, I'll keep working on this but in the meantime there's obviously a certain risk that a given MPAS grid cell happens to end up in no region according to the region masks.

**Comment by xylar** [comment]
I have a partial solution to this issue that I will probably submit a PR for once we figure out how we want to handle #60.  My solution will also partially address #62 by using the original [IHO sea areas](http://www.marineregions.org/sources.php#iho) data and adding scripts to `feature_creation_scripts` that recreate the regions that we currently have, moving portions of the South Atlantic and South Pacific into the Southern Ocean.

With this solution, there will still be small gaps between the land coverage and the ocean regions in many places and several small islands erroneously included in many ocean regions, but Tasmania and New Zealand will not be part of the Southern Ocean region.  These issues are proving harder to address in a robust way, and will likely wait for a second PR.

**Comment by xylar** [comment]
I'm closing this as it is very stale and we seem to be okay with having this issue.
