### ISSUE TITLE
Generalize plotting to work from geojson / shapely instance

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/geometric_features#46]
Plotting currently operates on geojson in an ad-hoc fashion.  To generalize we could:

 1. produce shapely instance from geojson file (readily done via something like 
`shape = shapely.geometry.shape(feature['geometry'])`)
 2. plot based on type of shapely instance (e.g., generalize existing [descartes library ](https://bitbucket.org/sgillies/descartes))

**Comment by pwolfram** [comment]
I believe this should be handled in general by #48 (potentially following a minor edit to `plot_features.py`), would you concur @xylar?  If so, once we merge #48, we can close this issue.

**Comment by xylar** [comment]
I think this issue is addressed sufficiently by #48.  Types other than `Polygon`, `MultiPolygon`, `LineString`, `MultiLineString` and `Point` are not supported elsewhere in this repo (e.g. in utils) so I don't think they should reasonably be expected to be supported by the plotting script.

**Comment by xylar** [comment]
Oops, shouldn't close this until #48 is merged...
