### ISSUE TITLE
Antarctica_IMBIE26 and Antarctica_IMBIE27 have the same geometry

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/geometric_features#5]
The `Antarctica_IMBIE26` region (the basin for Larsen C) was not added correctly and instead contains the same geometry as `Antarctica_IMBIE27`.

 ```
$ diff Antarctica_IMBIE26/region.geojson Antarctica_IMBIE27/region.geojson
6c6
< 			"name": "Antarctica_IMBIE26",
---
> 			"name": "Antarctica_IMBIE27",
8c8
< 			"tags": "AntarcticPenninsulaIMBIE;LarsenCIceShelfDrainage",
---
> 			"tags": "AntarcticPenninsulaIMBIE",
```

**Comment by stephenprice** [comment]
Ugh. OK, I'll dig into this early next week. I'm going to get back to working on some of the regions stuff then anyway. Thanks for pointing out the mistake. Let me know if that is soon enough.

**Comment by xylar** [comment]
Yep, that's fine.  I'm working on ice shelves, which will make use of the basins but I'm still more in the mode where I'm figuring out how to do it and I can do that without the Larsen C basin.

**Comment by stephenprice** [comment]
Resolved - see [here](https://github.com/MPAS-Dev/geometric_features/blob/master/landice/region/Antarctica_IMBIE26/region.geojson)
