### ISSUE TITLE
manipulate_features.py has identical functionality to merge_features.py

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/geometric_features#50]
I think that @douglasjacobsen had intended to make `manipulate_features.py` be a general script that could perform several operations on features.  However, the current version in the repository is identical to `merge_features.py` other than having a command line argument for an operation and a docstring that describes functionality it doesn't actually implement.

Unless a functioning version of this script will be added to the repo, I suggest we delete this script.

**Comment by xylar** [comment]
@pwolfram, what do you think?

**Comment by pwolfram** [comment]
@xylar, here is the PR #51 corresponding to this issue.  I completely agree.
