### ISSUE TITLE
Plotting error with moll projection for combined Atlantic and Southern Ocean

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/geometric_features#53]
Using the file at https://gist.github.com/43b8c23a27a84da35eadd9304a1b3753, there is a plotting error for the moll projection (which does not show up for moll2):

![screenshot 2016-09-26 16 18 41](https://cloud.githubusercontent.com/assets/4295853/18853904/fbe37422-8404-11e6-8e99-7a51c6bcd7eb.png)

Script to reproduce error from repository root:

```bash
mkdir test_feature_collection
cd test_feature_collection/
ln -s ../ocean/region/North_Atlantic_Ocean/region.geojson NA_region.geojson
ln -s ../ocean/region/South_Atlantic_Ocean/region.geojson SA_region.geojson
ln -s ../ocean/region/Southern_Ocean/region.geojson SO_region.geojson
cd ..
./merge_features.py -d test_feature_collection/ -o AO_SO.geojson
./plot_features.py -f AO_SO.geojson 
```

Note, found in the process of testing #52.  I believe this is a plotting error but it could be an error with preliminary changes in #52.

**Comment by pwolfram** [comment]
Going further:

```bash
./difference_features.py -f AO_SO.geojson -m landice/region/Antarctica_IMBIE1/region.geojson -o AO_SO_masked.geojson
./plot_features.py -f AO_SO_masked.geojson 
```

moll is even more visibly messed up (geojson file at https://gist.github.com/79c3cc90ef72ad8320e799c4a54eb203)...

![screenshot 2016-09-26 16 39 28](https://cloud.githubusercontent.com/assets/4295853/18854331/d6425f14-8407-11e6-83a1-dd29efedb4d9.png)

**Comment by xylar** [comment]
@pwolfram, I can reproduce these bugs and will look into them when I have a chance.

**Comment by xylar** [comment]
@pwolfram, I strongly suspect this is a bug in how shapes including the south (or presumably also the north) pole are handled in cartopy for this projection.  It should be pretty easy to set up an example where we plot a box similar to the SouthernOcean in a simplified script to indicate the problem.  Note that there are glitches in the Antarctic land coverage in both `moll` and `moll2` projections as well.
Anyway, I don't think this is an issue for this repo.  Please close if you agree and open an issue with cartopy instead.

**Comment by xylar** [comment]
@pwolfram, here is a simpler script demonstrating that the problem is with cartopy, not with our plotting routine:
https://gist.github.com/xylar/b5e1835f031d122d98196ba52cacf027

**Comment by pwolfram** [comment]
@xylar, I agree.  I'll submit an issue with them, will pass on your gist, and reference this issue.

**Comment by pwolfram** [comment]
The issue is https://github.com/SciTools/cartopy/issues/802, I'm closing this PR for now.
