### ISSUE TITLE
Update critical passages with depths based on bathymetry

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/geometric_features#59]
Currently, critical passages have depth properties that were chosen ad hoc to ensure the ocean was deep enough to allow flow along the passage.  A better method would be to break each critical passage into a number of smaller features (say 0.1 degrees long), each with its own depth taken from the ETOPO1 bathymetry.  This way, critical passages could be used without harm in high resolution and lower resolution setups alike.

**Comment by mark-petersen** [comment]
@xylar thanks for this post.  I agree this would make our critical passage routines applicable to all resolutions.

An additional note is that anything we add to initialization now needs to be backwards compatible, so we can still make old meshes when we make small changes (add new tracers, say)

**Comment by xylar** [comment]
@mark-petersen, in fact the changes @pwolfram just committed could theoretically break backward compatibility already by rounding coordinates slightly differently in the geojson files.  We really need to test that ASAP.

**Comment by xylar** [comment]
We discussed this and decided it's a feature we don't want.
