### ISSUE TITLE
Create develop branch or an ACME v1 tag

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/geometric_features#60]
We need to create a develop branch and/or a tag for ACME v1.  Presumably we need to stop making merges to master except where compatible with ACME v1.  This is because we need a way to recreate ACME initial conditions using features from the repo.

**Comment by xylar** [comment]
@mark-petersen, I could use your thoughts on how to do this best.

**Comment by xylar** [comment]
@matthewhoffman, I know you're not really using this repo, but maybe you have some thoughts as well?

**Comment by xylar** [comment]
Part if this process would be figuring out where we need to branch off.  Hopefully everything we've recently committed hasn't broken the the ability to make ACME initial conditions, but if it has we need to figure out how far we need to backtrack to make an ACME v1 compatible tag.

**Comment by matthewhoffman** [comment]
@xylar , I have only used this repo in passing, but I'm happy to help coordinate ACME-related branching issues.  I think your assessment is correct that having a branch would ensure robustness of the ACME workflow.  I also agree with your assessment of first needing to identify the commit at which ACME still works (which could be the current HEAD) as the first step.  I would suggest waiting to make a release branch until the MPAS component code release branches are made, but if there is a bunch of work going on now or soon in this repo unrelated to ACME v1, making the release branch sooner could make more sense.

**Comment by xylar** [comment]
@matthewhoffman, thanks, that's very helpful.  There are a couple of pull requests and issues in the pipeline that would break ACME initial conditions, but they can remain there for the time being.  But I also think this repo could function largely independently from the other MPAS repos in terms of making a development branch.  There is also a difference here in that we would presumably be making the `develop` branch as opposed to the `release` branch (or perhaps both together).  To me, it makes sense to try to do that sooner rather than later so there's no risk of putting `develop` code onto master in the interim.  It's easy enough to merge `develop` with `master` but much messier to revert `master` when problems are caught.

**Comment by xylar** [comment]
As I note in #61, I am confident that recent changes to this repo won't affect ACME initial conditions generated with the current `MPAS-Dev/geometric_features/master`.  I think now is the time to create release and develop branches and maybe stop using master.

**Comment by xylar** [comment]
@MPAS-Dev/all-developers, I would like to create a `develop` branch for `geometric_features`.  This would allow improvements that modify existing features without interfering with the ability to recreate the initial conditions currently used by ACME through `master`.

If there are objections, please raise them here and within the next week or so.

**Comment by mark-petersen** [comment]
@xylar Having both `develop` and `master` branches would require more maintenance and could be confusing.  I want to make sure we have good reasons.  The alternative is to have a single branch and to just adding tags so we can reference back to a particular commit used to make, say, a particular generation of meshes.

A few questions:
1. What is the down side of a single branch with tags, i.e. `ACME V3 grids`
2. If we had both  `develop` and `master` branches, would they diverge, or would `master` simply lag `develop`.  

I think the core decision is whether this repo is complex enough that a particular "frozen" version will need bug fixes at a later time, and the main branch has diverged so backwards compatibility is broken.  If **yes**, we should make a release branch (or frozen branch) that only gets bug fixes while the main branch continues to develop.  If **no**, we should simply make a tag.

**Comment by xylar** [comment]
@mark-petersen, these are good points and good questions.

We have two sets of divergent needs for this repo.  First, we need to be able to add features to the repo.  This will typically (though perhaps not always!) do no harm to the initialization of MPAS-Ocean (and presumably at some point other components) for ACME.  It seems like this is what `master` could be used for.

At the same time, we need a way to modify existing features and add new functionality.  Such activities *could* mess with our ability to recreate ACME initial conditions.  This is where I see `develop` playing a role.

Each time we want to merge `develop` into `master`, we would want to first make sure there is an appropriate tag for ACME initial conditions.

I'm not attach to these particular names, but right now I have code and features for improving the land ice masks that I can't merge (and is moldering on its own branch) because this would mess with ACME initial conditions.  This is why I would like to push for a solution.

**Comment by xylar** [comment]
A tag was created for E3SM v3 grids for MPAS-O and MPAS-SeaIce:

https://github.com/MPAS-Dev/geometric_features/tree/E3SMv3grids
