### ISSUE TITLE
Provenance for ocean, ice shelf and land ice regions

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/geometric_features#62]
Scripts should be added to `feature_creation_scripts` that can recreate all the features in the repository that weren't created by hand.

**Comment by xylar** [comment]
@stephenprice, if you can give me whatever scripts you used to create the Antarctic features at some point, I can see that they make their way to the repo so we can thereby document how we created the features we're using.  I'll do the same for ocean and ice shelf features as I find time.

**Comment by pwolfram** [comment]
@xylar, should we additionally be somehow documenting the workflow used to produce each derivative feature via a "history" property that records the commands and git hash used to produce the feature?

**Comment by xylar** [comment]
@pwolfram, I guess that's probably right.  I don't know how to do that effectively so maybe you should make it a separate issue or design document or whatever you think is appropriate.

**Comment by xylar** [comment]
Addressed by #64
