### ISSUE TITLE
groupName removed from geojson files when running setup_MOC_basins and setup_ocean_basins

### ISSUE THREAD

**Issue by milenaveneziani** [MPAS-Dev/geometric_features#65]
After running these two scripts in driver_scripts: setup_MOC_basins and setup_ocean_basins, the resulting geojson files are missing the groupName property.

**Comment by pwolfram** [comment]
@milenaveneziani, I think this PR https://github.com/MPAS-Dev/geometric_features/pull/52 may have removed the `groupName` property and I'll take a look to see if I can quickly fix this issue.

**Comment by pwolfram** [comment]
It looks like it was removed much earlier than even that @milenaveneziani.  It was a feature that never appears to be fully used and was replaced in terms of function by tags, unless I'm mistaken.  For instance, in commit `0d6006be285580949d2fb4a0bdfa4d03bb68b2b7`, 

```bash
┌─[pwolfram][shapiro][~/Documents/MPAS_pull_requests/geometric_features_groupName][15:34][±][ ✓]
└─▪ git grep groupName
combine_features.py:109:out_file.write(' "groupName": "enterNameHere",\n')
difference_features.py:110:out_file.write(' "groupName": "enterNameHere",\n')
fix_features_at_antimeridian.py:130:out_file.write(' "groupName": "enterNameHere",\n')
fix_features_at_prime_meridian.py:92:out_file.write(' "groupName": "enterNameHere",\n')
merge_features.py:107:out_file.write(' "groupName": "enterNameHere",\n')
simplify_features.py:84:out_file.write(' "groupName": "enterNameHere",\n')
tag_features.py:68:out_file.write(' "groupName": "enterNameHere",\n')
```

Group names never appear to have been specified.  In recent PRs they appear to have been silently depreciated by tags, e.g., see `merge_features.py`.  I'm going to submit a PR to clean this up and remove `groupName` completely from the code.  Thanks for finding this inconsistency.

**Comment by milenaveneziani** [comment]
@pwolfram: I don't think it is correct to remove the groupName. I had an email exchange with @xylar prior to submitting this issue and he thought we needed to put it back. I think 'tags' serve a different purpose, although @douglasjacobsen could add more details on this. My feeling is that 'groupName' sits above tags and we need it to specify groups of regions. Say: "OceanBasinsMOC" or "SouthernOceanRegions", etc.

**Comment by pwolfram** [comment]
@milenaveneziani, can you please provide more information on a use case for `groupName`?  When would a feature be tagged with this property, for instance?  Is `groupName` used as a filter to specify which of certain properties should be selected, for instance?

I think the more information we have about the usage of this feature the better because right now it is not used at all and is vestigial code that should be removed, e.g., in #66.

**Comment by milenaveneziani** [comment]
@pwolfram: I think @xylar or @douglasjacobsen are better positioned to answer the question 'groups' vs 'tags'. The groupName usage I had in mind is to group OceanBasins and OceanBasinsMOC, for example. The first group includes 6 ocean basins that we have defined giving special attention at how we defined the Southern Ocean (it includes the Arctic, SO, Atlantic, Pacific, Indian, and Mediterranean). The second group includes only regions that are better suited for the MOC and MHT calculations (no major channels or openings in their east and west boundaries).

**Comment by pwolfram** [comment]
@milenaveneziani, this is starting to come back to me: the `groupName` is used in MPAS and not just in this repo, right?  If so, it would be a property that could be used in analysis members, right?  If this is the case we need to have a discussion about what functionality is needed to create groups.

**Comment by milenaveneziani** [comment]
yes, I think so. I personally don't know how we would use 'tags', but I think we definitely want to keep groups.

**Comment by xylar** [comment]
@milenaveneziani and @pwolfram, it seems like group names should be addressed somehow as part of the driver scripts.  I do not think #66 makes sense until we figure out how this should be handled.  Presumably the group name may be related to a tag used to find regions but it is not obvious that tags serve as a substitute for the group name or that group names can, in general, be derived from tags.

Let's talk about this more when I get back unless you two are very sure you have a working solution.

**Comment by pwolfram** [comment]
@milenaveneziani, do you have a pressing need for the groupName feature?  Otherwise I propose we wait until we can entrain @xylar into the conversation while he is not on travel / vacation.

**Comment by douglasjacobsen** [comment]
Here is some more information about `groupName`: https://github.com/MPAS-Dev/geometric_features/pull/66#issuecomment-251691765

Additionally, the following comment has information about when groupName disappeared.
