### ISSUE TITLE
Testing to ensure requirements are met

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/geometric_features#68]
Following the accidental removal of `groupName`, we should consider implementing an integrated testing environment that ensures requirements are met, e.g., minimally that `groupName` and other properties are outputed at appropriate points within the workflow.  Note, there are probably other things that should be tested.

cc @xylar, @milenaveneziani

**Comment by xylar** [comment]
@pwolfram, when you have a free moment (i.e. after March 15th), could you add travis CI to this repo like you did for MPAS-Analysis?  If you get an example test going, I'd be glad to help add meaningful tests of both individual scripts and more complex workflows.

**Comment by pwolfram** [comment]
@xylar, sounds great.  I have it on my calendar.

**Comment by pwolfram** [comment]
Closed by #88.
