### ISSUE TITLE
setup_MOC_basins re-defines three Basin regions that are already defined in setup_ocean_basins

### ISSUE THREAD

**Issue by milenaveneziani** [MPAS-Dev/geometric_features#70]
Atlantic_Basin.geojson, Indian_Basin.geojson and Pacific_Basin.geojson are defined by setup_ocean_basins.py (together with 3 more Ocean Basin regions). They are then re-defined in setup_MOC_basins.py and they are different from the equally-named features defined in setup_ocean_basins.

To avoid confusion and also unify the way that all this basin-scale regions (and their groupnames) are defined it seems like we should have one single script that:
- creates Ocean Basins (groupName=OceanBasinRegionsGroup);
- creates MOC Basins (groupName=MOCBasinRegionsGroup), without overriding the previously defined Basin features;
- creates MOC southern transects, as in issue #69;
- defines the group for the Global\* features (already in the repo, in ocean/region) as the same groupName as the other Ocean Basins.

**Comment by pwolfram** [comment]
Note, this issue was discovered while fullfilling #67.

**Comment by xylar** [comment]
As I mention in #73, I do not think this is the right approach to cleaning up the driver files.  Instead, I think we want to create the fewest number of `geojson` files necessary to create the masks we need from each set of features.  Perhaps the driver scripts should also delete any intermediate files they create along the way so there is not any confusion about what the final product(s) of each script are.

**Comment by xylar** [comment]
@milenaveneziani, can you clarify this bullet point from above?
> defines the group for the Global* features (already in the repo, in ocean/region) as the same groupName as the other Ocean Basins.

The features you seem to be referring to are `Global_Ocean_65N_to_65S` and `Global_Ocean_90S_to_60S` but it is not clear what you would like to have happen with these features.    The second of these features is used to create the land coverage used in MPAS-O by combining the `natural_earth` feature north of 60S with one or the other `bedmap2` feature south of that latitude.  So I don't see why we would want to do anything with it in a new, combined driver script, (say `setup_ocean_MOC_and_basins.py`).  As for the former, I don't know what it's used for so it's unclear how it relates to the ocean basins.

**Comment by milenaveneziani** [comment]
@xylar: thanks for addressing all these issues at once. I will be going slowly through them between today and tomorrow.
From what understand, your main suggestion is to bundle up all MOC and OceanBasin features in two single features and define their groups in the process, using the respective drivers (bypassing the merge_feature step). I think this is a great idea: the less steps and the less likely we are to make mistakes.
And yes, I would delete the intermediate geojson files.

Finally about the Global* features: the only one we care about for this issue/PR is Global_Ocean_65N_to_65S. That region can be used to compare OHC directly with a specific observational data set, and that is the reason why the feature was created in the first place. So, it should be included in the MOCbasins group.

**Comment by xylar** [comment]
> That region can be used to compare OHC directly with a specific observational data set, and that is the reason why the feature was created in the first place. So, it should be included in the MOCbasins group.

Ah, great!  Now I get it.  That will be very easy to add.

**Comment by xylar** [comment]
@milenaveneziani can correct me if I'm wrong but I think it is now fully addressed by #74.

**Comment by xylar** [comment]
Ah, no, it doesn't create the southern boundaries so not yet complete.

**Comment by xylar** [comment]
I'm going to close this issue because we seem to be pretty sure at this point that we won't define the MOC southern boundaries in this repo.  We have at least attempted to define it in MPAS-Tools instead (https://github.com/MPAS-Dev/MPAS-Tools/pull/147).
