### ISSUE TITLE
Update of Maritime Boundaries Geodatabase

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/geometric_features#76]
We may want to consider updating our regions based on the new standards published at http://www.marineregions.org, e.g., see the email below I received this morning:

> Dear Marine Regions User,
 
>MarineRegions.org is proud to launch the new version of the Maritime Boundaries Geodatabase. In this new release, Marine Regions updates the global Exclusive Economic Zones (EEZ) (version 9), and launches global datasets for Territorial Seas (TS), Contiguous Zones (CZ), Internal Waters (IW) and Archipelagic Waters (AW). The global baseline used in this new version is a combination of the publically available straight and archipelagic baselines and the coastline as a proxy for the low-water line. The source for the straight baselines is the United Nations repository on maritime claims, together with national publications on maritime delimitations and agreements. The ESRI Countries 2014 database has been used as the primary source for the Maritime Boundaries coastline. The coastline was further updated with reefs data extracted from the Coral Reef Distribution database from UNEP for the countries where reefs were fundamental for the correct calculation of the maritime areas.
 
>With the new release, we hope to further serve the global marine data user community working on geospatial analysis. As Marine Regions depends on data and knowledge sharing from global, European, regional and national data providers and relevant experts, we aim to set up Collaboration Agreements with our users and data providers. An example template of a Collaboration Agreement can be found online, please contact info@marineregions.org if your organization is interested to explore this collaboration.
 
>All datasets from marineregions.org’s Maritime Boundaries Geodatabase continue to be the only freely-available global datasets on the World’s Maritime Boundaries.
 
>With Kind Regards
 
>The Marine Regions Team

I'd recommend we try to stay as faithful to this "standard" as possible, but at the same time I don't think we really can afford to change out region definitions too frequently either.  This is obviously an issue up for broad discussion.

**Comment by xylar** [comment]
@pwolfram, I don't think the IHO shape files that we used have been changed in the abovementioned update:
http://www.marineregions.org/downloads.php#iho

So I don't think the changes are relevant to us.  There are several issues with incompatibility of the IHO seas with one another and with the Natural Earth coastline that I'm trying to deal with (see #44).  I will try to make whatever modifications I do apply be something that could be repeated if/when the IHO sea areas do get updated.

Please close this issue if you agree that the IHO sea areas are not affected by the updates you discussed.

**Comment by pwolfram** [comment]
Agreed @xylar, thanks for the review on this-- I am glad to see that this doesn't affect us but wanted to make sure just in case.
