### ISSUE TITLE
Consider use of salem to streamline masking and manipulation

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/geometric_features#80]
[salem](http://salem.readthedocs.io/en/stable/index.html) may be useful in the current workflow to produce masks and further manipulate data to extend existing functionality using [shapely](http://toblerity.org/shapely/manual.html) as well as [cartopy](http://scitools.org.uk/cartopy/).

**Comment by xylar** [comment]
Wow, yes, looks promising from the examples.
